use crate::attrs::CellAttributes;
use crate::cell::Cell;
use crate::cursor::Cursor;

/// A single row in the terminal grid.
///
/// Tracks whether the row was soft-wrapped (i.e. content continued from the
/// right margin onto this row without an explicit newline). This flag drives
/// the reflow algorithm on resize.
#[derive(Debug, Clone)]
pub struct Row {
    pub cells: Vec<Cell>,
    /// `true` when this row was generated by auto-wrap (soft wrap).
    /// The next row is a continuation of this logical line.
    pub wrapped: bool,
}

impl Row {
    /// Create a blank row of the given width.
    pub fn new(cols: usize) -> Self {
        Self {
            cells: (0..cols).map(|_| Cell::default()).collect(),
            wrapped: false,
        }
    }

    /// Create a row from existing cells.
    pub fn from_cells(cells: Vec<Cell>, wrapped: bool) -> Self {
        Self { cells, wrapped }
    }
}

impl std::ops::Deref for Row {
    type Target = Vec<Cell>;
    fn deref(&self) -> &Vec<Cell> {
        &self.cells
    }
}

impl std::ops::DerefMut for Row {
    fn deref_mut(&mut self) -> &mut Vec<Cell> {
        &mut self.cells
    }
}

/// The terminal grid — a 2D array of cells representing the visible viewport.
#[derive(Debug)]
pub struct Grid {
    /// Grid rows stored in order (top to bottom)
    cells: Vec<Row>,
    /// Number of columns
    pub cols: usize,
    /// Number of rows
    pub rows: usize,
    /// Current cursor position
    pub cursor: Cursor,
    /// Current SGR attributes for new characters
    pub current_attrs: CellAttributes,
}

impl Grid {
    pub fn new(cols: usize, rows: usize) -> Self {
        let cells = (0..rows).map(|_| Row::new(cols)).collect();

        Self {
            cells,
            cols,
            rows,
            cursor: Cursor::default(),
            current_attrs: CellAttributes::default(),
        }
    }

    /// Get a reference to the cell at (col, row).
    #[inline]
    pub fn cell(&self, col: usize, row: usize) -> Option<&Cell> {
        self.cells.get(row).and_then(|r| r.cells.get(col))
    }

    /// Get a mutable reference to the cell at (col, row).
    #[inline]
    pub fn cell_mut(&mut self, col: usize, row: usize) -> Option<&mut Cell> {
        self.cells.get_mut(row).and_then(|r| r.cells.get_mut(col))
    }

    /// Write a character at the current cursor position and advance.
    pub fn write_char(&mut self, ch: char) {
        let col = self.cursor.col;
        let row = self.cursor.row;
        let attrs = self.current_attrs;

        if col < self.cols && row < self.rows {
            if let Some(cell) = self.cell_mut(col, row) {
                cell.content.clear();
                cell.content.push(ch);
                cell.attrs = attrs;
                cell.width = 1;
            }
            self.cursor.col += 1;
        }
    }

    /// Get a row as a slice of cells.
    pub fn row(&self, row: usize) -> Option<&[Cell]> {
        self.cells.get(row).map(|r| r.cells.as_slice())
    }

    /// Get the full Row struct (with wrapped flag).
    pub fn row_ref(&self, row: usize) -> Option<&Row> {
        self.cells.get(row)
    }

    /// Get a mutable reference to the Row struct.
    pub fn row_mut(&mut self, row: usize) -> Option<&mut Row> {
        self.cells.get_mut(row)
    }

    /// Clear the entire grid.
    pub fn clear(&mut self) {
        for row in &mut self.cells {
            for cell in row.cells.iter_mut() {
                cell.clear();
            }
            row.wrapped = false;
        }
    }

    /// Scroll the grid up by one line, adding a blank line at the bottom.
    /// Returns the row that was scrolled off the top.
    pub fn scroll_up(&mut self) -> Row {
        let top_row = self.cells.remove(0);
        self.cells.push(Row::new(self.cols));
        top_row
    }

    /// Clear a single row.
    pub fn clear_row(&mut self, row: usize) {
        if let Some(r) = self.cells.get_mut(row) {
            for cell in r.cells.iter_mut() {
                cell.clear();
            }
            r.wrapped = false;
        }
    }

    /// Clear cells in a row from `start` (inclusive) to `end` (exclusive).
    pub fn clear_range_in_row(&mut self, start: usize, end: usize, row: usize) {
        if let Some(r) = self.cells.get_mut(row) {
            for col in start..end.min(r.cells.len()) {
                r.cells[col].clear();
            }
        }
    }

    /// Scroll a region (top..=bottom) up by one line. Returns the removed top row.
    pub fn scroll_region_up(&mut self, top: usize, bottom: usize) -> Row {
        if top >= self.cells.len() || bottom >= self.cells.len() || top > bottom {
            return Row::new(0);
        }
        let removed = self.cells.remove(top);
        self.cells.insert(bottom, Row::new(self.cols));
        removed
    }

    /// Scroll a region (top..=bottom) down by one line.
    pub fn scroll_region_down(&mut self, top: usize, bottom: usize) {
        if top >= self.cells.len() || bottom >= self.cells.len() || top > bottom {
            return;
        }
        self.cells.remove(bottom);
        self.cells.insert(top, Row::new(self.cols));
    }

    /// Insert a blank line at `row`, pushing lines down. Bottom line is discarded.
    pub fn insert_line(&mut self, row: usize, bottom: usize) {
        if row > bottom || bottom >= self.cells.len() {
            return;
        }
        self.cells.remove(bottom);
        self.cells.insert(row, Row::new(self.cols));
    }

    /// Delete the line at `row`, shifting lines up. A blank line is added at `bottom`.
    pub fn delete_line(&mut self, row: usize, bottom: usize) {
        if row > bottom || bottom >= self.cells.len() {
            return;
        }
        self.cells.remove(row);
        self.cells.insert(bottom, Row::new(self.cols));
    }

    /// Insert `n` blank cells at (col, row), shifting existing cells right.
    pub fn insert_blank_cells(&mut self, col: usize, row: usize, n: usize) {
        if let Some(r) = self.cells.get_mut(row) {
            for _ in 0..n {
                if col < r.cells.len() {
                    r.cells.insert(col, Cell::default());
                    r.cells.truncate(self.cols);
                }
            }
        }
    }

    /// Delete `n` cells at (col, row), shifting remaining cells left.
    pub fn delete_cells(&mut self, col: usize, row: usize, n: usize) {
        if let Some(r) = self.cells.get_mut(row) {
            let end = (col + n).min(r.cells.len());
            r.cells.drain(col..end);
            while r.cells.len() < self.cols {
                r.cells.push(Cell::default());
            }
        }
    }

    /// Simple resize without reflow (used for alternate screen).
    pub fn resize(&mut self, new_cols: usize, new_rows: usize) {
        // Adjust row count
        while self.cells.len() < new_rows {
            self.cells.push(Row::new(new_cols));
        }
        self.cells.truncate(new_rows);

        // Adjust column count per row
        for row in &mut self.cells {
            while row.cells.len() < new_cols {
                row.cells.push(Cell::default());
            }
            row.cells.truncate(new_cols);
        }

        self.cols = new_cols;
        self.rows = new_rows;

        // Clamp cursor
        if self.cursor.col >= new_cols {
            self.cursor.col = new_cols.saturating_sub(1);
        }
        if self.cursor.row >= new_rows {
            self.cursor.row = new_rows.saturating_sub(1);
        }
    }

    /// Resize with reflow: joins wrapped lines, re-breaks at new width, and
    /// distributes rows between scrollback and grid.
    ///
    /// Returns the new (col, row) for the cursor position after reflow.
    pub fn resize_with_reflow(
        &mut self,
        new_cols: usize,
        new_rows: usize,
        scrollback: &mut crate::buffer::ScrollbackBuffer,
    ) -> (usize, usize) {
        // 1. Compute the cursor's absolute position (in logical-line space)
        let old_cursor_abs_row = scrollback.len() + self.cursor.row;
        let old_cursor_col = self.cursor.col;

        // 2. Drain all grid rows into scrollback (preserving wrapped flags)
        for row in self.cells.drain(..) {
            scrollback.push(row);
        }

        // 3. Join wrapped rows into logical lines, then re-break at new_cols
        let all_rows = scrollback.drain_all();
        let logical_lines = join_wrapped_rows(all_rows);
        let mut reflowed: Vec<Row> = Vec::new();

        // Track cursor through reflow
        let mut cursor_new_abs_row = 0usize;
        let mut cursor_new_col = old_cursor_col;
        let mut abs_in = 0usize; // absolute row counter in old rows

        for line in &logical_lines {
            let broken = break_line_at_width(&line.cells, new_cols);
            let broken_count = broken.len();

            // Find cursor in this logical line
            for (i, _old_row) in line.source_rows.iter().enumerate() {
                let row_start_in_line = i * self.cols; // approx offset in logical chars
                if abs_in + i == old_cursor_abs_row {
                    // Cursor was in this source row at old_cursor_col
                    let char_offset = row_start_in_line + old_cursor_col;
                    // Map to new row/col
                    if new_cols > 0 {
                        cursor_new_abs_row = reflowed.len() + char_offset / new_cols;
                        cursor_new_col = char_offset % new_cols;
                    }
                }
            }

            for (bi, mut row) in broken.into_iter().enumerate() {
                // Pad to new_cols
                while row.cells.len() < new_cols {
                    row.cells.push(Cell::default());
                }
                row.cells.truncate(new_cols);
                // All but the last broken segment are wrapped
                row.wrapped = bi + 1 < broken_count;
                reflowed.push(row);
            }

            abs_in += line.source_rows.len();
        }

        // 4. Split reflowed rows into scrollback + grid.
        //    Anchor so the cursor stays visible in the grid.
        let total = reflowed.len();
        let grid_start = if total <= new_rows {
            // Everything fits — no scrollback needed
            0
        } else {
            // Anchor to cursor: keep cursor visible, as close to its natural
            // position as possible without scrolling past the end.
            let ideal = cursor_new_abs_row.saturating_sub(new_rows.saturating_sub(1));
            ideal.min(total.saturating_sub(new_rows))
        };

        // Scrollback gets everything above the grid
        scrollback.clear();
        for row in reflowed.drain(..grid_start) {
            scrollback.push(row);
        }

        // Grid gets the remaining rows
        self.cells = reflowed;
        while self.cells.len() < new_rows {
            self.cells.push(Row::new(new_cols));
        }
        self.cells.truncate(new_rows);

        self.cols = new_cols;
        self.rows = new_rows;

        // 5. Compute final cursor position relative to the grid
        let new_cursor_row = cursor_new_abs_row.saturating_sub(grid_start);
        let new_cursor_col = cursor_new_col.min(new_cols.saturating_sub(1));
        let new_cursor_row = new_cursor_row.min(new_rows.saturating_sub(1));

        self.cursor.col = new_cursor_col;
        self.cursor.row = new_cursor_row;

        (new_cursor_col, new_cursor_row)
    }
}

/// A logical line is a sequence of physical rows joined at wrap boundaries.
struct LogicalLine {
    cells: Vec<Cell>,
    source_rows: Vec<usize>, // indices of original rows (for cursor tracking)
}

/// Join consecutive wrapped rows into logical lines.
fn join_wrapped_rows(rows: Vec<Row>) -> Vec<LogicalLine> {
    let mut lines: Vec<LogicalLine> = Vec::new();
    let mut current_cells: Vec<Cell> = Vec::new();
    let mut current_sources: Vec<usize> = Vec::new();

    for (i, row) in rows.into_iter().enumerate() {
        // Trim trailing default cells from the row
        let mut trimmed = row.cells;
        while trimmed.last().is_some_and(|c| c.is_empty()) {
            trimmed.pop();
        }

        current_cells.extend(trimmed);
        current_sources.push(i);

        if !row.wrapped {
            // End of logical line
            lines.push(LogicalLine {
                cells: std::mem::take(&mut current_cells),
                source_rows: std::mem::take(&mut current_sources),
            });
        }
    }

    // Flush any remaining (shouldn't happen if last row has wrapped=false)
    if !current_cells.is_empty() {
        lines.push(LogicalLine {
            cells: current_cells,
            source_rows: current_sources,
        });
    }

    lines
}

/// Break a logical line's cells into physical rows of `cols` width.
fn break_line_at_width(cells: &[Cell], cols: usize) -> Vec<Row> {
    if cells.is_empty() || cols == 0 {
        return vec![Row::new(cols)];
    }

    let mut rows: Vec<Row> = Vec::new();
    let mut col = 0usize;
    let mut current_cells: Vec<Cell> = Vec::new();

    let mut i = 0;
    while i < cells.len() {
        let cell = &cells[i];
        let w = cell.width.max(1) as usize;

        // Wide char doesn't fit — move to next row
        if w == 2 && col + 1 >= cols {
            // Fill remaining with space
            while current_cells.len() < cols {
                current_cells.push(Cell::default());
            }
            rows.push(Row::from_cells(current_cells, true));
            current_cells = Vec::new();
            col = 0;
            // Don't advance i — retry the wide char on the new row
            continue;
        }

        current_cells.push(cell.clone());
        col += 1;

        // For wide chars, also consume the continuation cell
        if w == 2 {
            if i + 1 < cells.len() && cells[i + 1].width == 0 {
                current_cells.push(cells[i + 1].clone());
                col += 1;
                i += 1;
            } else {
                // Missing continuation — add one
                let cont = Cell {
                    content: String::new(),
                    attrs: CellAttributes::default(),
                    width: 0,
                };
                current_cells.push(cont);
                col += 1;
            }
        }

        if col >= cols {
            rows.push(Row::from_cells(current_cells, true));
            current_cells = Vec::new();
            col = 0;
        }

        i += 1;
    }

    // Last segment (not wrapped since it ends the logical line)
    if !current_cells.is_empty() || rows.is_empty() {
        while current_cells.len() < cols {
            current_cells.push(Cell::default());
        }
        rows.push(Row::from_cells(current_cells, false));
    }

    // Last row is never wrapped (it's the end of a logical line)
    if let Some(last) = rows.last_mut() {
        last.wrapped = false;
    }

    rows
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::attrs::CellAttributes;

    fn make_cell(ch: char) -> Cell {
        Cell {
            content: String::from(ch),
            attrs: CellAttributes::default(),
            width: 1,
        }
    }

    fn make_row_from_str(s: &str, cols: usize, wrapped: bool) -> Row {
        let mut cells: Vec<Cell> = s.chars().map(make_cell).collect();
        while cells.len() < cols {
            cells.push(Cell::default());
        }
        cells.truncate(cols);
        Row::from_cells(cells, wrapped)
    }

    fn row_text(row: &Row) -> String {
        row.cells
            .iter()
            .map(|c| {
                if c.width == 0 {
                    return ' ';
                }
                c.content.chars().next().unwrap_or(' ')
            })
            .collect::<String>()
            .trim_end()
            .to_string()
    }

    #[test]
    fn test_reflow_wider() {
        // Two wrapped rows of 5 cols → resize to 10 cols → should merge
        let mut scrollback = crate::buffer::ScrollbackBuffer::new();
        let mut grid = Grid::new(5, 2);
        grid.cells[0] = make_row_from_str("ABCDE", 5, true);
        grid.cells[1] = make_row_from_str("FGHIJ", 5, false);

        grid.resize_with_reflow(10, 2, &mut scrollback);

        assert_eq!(grid.cols, 10);
        // The merged line "ABCDEFGHIJ" fits in one row at 10 cols (top-anchored)
        assert_eq!(row_text(&grid.cells[0]), "ABCDEFGHIJ");
        assert_eq!(row_text(&grid.cells[1]), "");
        assert_eq!(scrollback.len(), 0);
    }

    #[test]
    fn test_reflow_narrower() {
        // One row of 10 cols → resize to 5 cols → should split into 2 wrapped rows
        let mut scrollback = crate::buffer::ScrollbackBuffer::new();
        let mut grid = Grid::new(10, 2);
        grid.cells[0] = make_row_from_str("ABCDEFGHIJ", 10, false);

        grid.resize_with_reflow(5, 2, &mut scrollback);

        assert_eq!(grid.cols, 5);
        assert_eq!(row_text(&grid.cells[0]), "ABCDE");
        assert!(grid.cells[0].wrapped);
        assert_eq!(row_text(&grid.cells[1]), "FGHIJ");
        assert!(!grid.cells[1].wrapped);
    }

    #[test]
    fn test_reflow_preserves_hard_newline() {
        // Two rows with hard newlines should stay separate after reflow
        let mut scrollback = crate::buffer::ScrollbackBuffer::new();
        let mut grid = Grid::new(5, 3);
        grid.cells[0] = make_row_from_str("ABC", 5, false); // hard newline
        grid.cells[1] = make_row_from_str("DEF", 5, false); // hard newline
        grid.cells[2] = Row::new(5);

        grid.resize_with_reflow(10, 3, &mut scrollback);

        assert_eq!(row_text(&grid.cells[0]), "ABC");
        assert_eq!(row_text(&grid.cells[1]), "DEF");
        assert_eq!(row_text(&grid.cells[2]), "");
    }

    #[test]
    fn test_reflow_cursor_tracking() {
        // Cursor at col 3, row 1 (second row), cols=5
        // Content: "ABCDE" (wrapped) + "FGHIJ"
        // Resize to 10 cols → merged into one row, cursor should be at col 8
        let mut scrollback = crate::buffer::ScrollbackBuffer::new();
        let mut grid = Grid::new(5, 2);
        grid.cells[0] = make_row_from_str("ABCDE", 5, true);
        grid.cells[1] = make_row_from_str("FGHIJ", 5, false);
        grid.cursor.col = 3;
        grid.cursor.row = 1;

        let (col, _row) = grid.resize_with_reflow(10, 2, &mut scrollback);

        assert_eq!(col, 8); // offset 5 + 3 = 8 in the merged line
    }

    #[test]
    fn test_alt_screen_no_reflow() {
        // Simple resize (for alt screen) should not reflow
        let mut grid = Grid::new(5, 2);
        grid.cells[0] = make_row_from_str("ABCDE", 5, true);
        grid.cells[1] = make_row_from_str("FGHIJ", 5, false);

        grid.resize(10, 2);

        // Should NOT merge — simple resize just pads
        assert_eq!(row_text(&grid.cells[0]), "ABCDE");
        assert_eq!(row_text(&grid.cells[1]), "FGHIJ");
    }

    #[test]
    fn test_reflow_wide_chars() {
        // Wide char (width=2) at col 4 of a 5-col grid can't fit → wraps
        let mut scrollback = crate::buffer::ScrollbackBuffer::new();
        let mut grid = Grid::new(5, 2);

        // Row: "ABCD" + wide_char(fills cols 4-5 which wraps)
        grid.cells[0] = Row::new(5);
        for (i, ch) in "ABCD".chars().enumerate() {
            grid.cells[0].cells[i] = make_cell(ch);
        }
        // Make last cell a space (wide char didn't fit, was put on next line)
        grid.cells[1] = Row::new(5);

        grid.resize_with_reflow(10, 2, &mut scrollback);

        // After reflow with wider grid, the content should not be corrupted
        assert_eq!(grid.cols, 10);
    }
}
