//! System tray icon — adds a notification-area icon with a context menu.
//!
//! `TrayIcon` wraps Win32 `Shell_NotifyIconW` for a system tray presence.
//! `TrayMenu` builds a context menu from entries that can be displayed on
//! right-click. Menu construction is fully testable without a window handle.

use std::mem;
use std::ptr;

use tracing::{error, info, warn};
use windows::Win32::Foundation::HWND;
use windows::Win32::UI::Shell::{
    NIF_ICON, NIF_MESSAGE, NIF_TIP, NIM_ADD, NIM_DELETE, NOTIFYICONDATAW, Shell_NotifyIconW,
};
use windows::Win32::UI::WindowsAndMessaging::{
    IDI_APPLICATION, LoadIconW, WM_APP, WM_LBUTTONDBLCLK, WM_LBUTTONUP, WM_RBUTTONUP,
};

/// Custom window message for tray icon callbacks.
pub const WM_TRAY_CALLBACK: u32 = WM_APP + 1;

/// Fixed tray icon identifier (one icon per window).
const TRAY_ICON_UID: u32 = 1;

/// Maximum tooltip length in characters (including null terminator).
/// The `szTip` field is `[u16; 128]`, so 127 usable chars + null.
const MAX_TOOLTIP_CHARS: usize = 127;

/// Standard menu entry IDs for the default tray menu.
pub const TRAY_ID_SHOW_HIDE: u32 = 1;
pub const TRAY_ID_NEW_TAB: u32 = 2;
pub const TRAY_ID_SETTINGS: u32 = 3;
pub const TRAY_ID_EXIT: u32 = 100;

/// Events generated by user interaction with the tray icon.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayClickEvent {
    LeftClick,
    RightClick,
    DoubleClick,
}

/// Parse the `lParam` from a `WM_TRAY_CALLBACK` message into a click event.
///
/// The low word of `lParam` carries the mouse message that triggered the
/// callback (e.g. `WM_LBUTTONUP`).
pub fn parse_tray_message(lparam: isize) -> Option<TrayClickEvent> {
    let msg = (lparam & 0xFFFF) as u32;
    match msg {
        WM_LBUTTONUP => Some(TrayClickEvent::LeftClick),
        WM_RBUTTONUP => Some(TrayClickEvent::RightClick),
        WM_LBUTTONDBLCLK => Some(TrayClickEvent::DoubleClick),
        _ => None,
    }
}

/// Encode a Rust string into a fixed-size wide buffer, truncating if needed.
///
/// Returns the buffer with a null terminator. Characters beyond `max_chars`
/// (excluding null) are silently dropped.
fn encode_wide_tooltip(text: &str, max_chars: usize) -> [u16; 128] {
    let mut buf = [0u16; 128];
    for (i, unit) in text.encode_utf16().take(max_chars).enumerate() {
        buf[i] = unit;
    }
    buf
}

/// A single entry in a tray context menu.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TrayMenuEntry {
    /// Unique command identifier dispatched on click.
    pub id: u32,
    /// Display label (empty string for separators).
    pub label: String,
    /// Whether the entry is clickable.
    pub enabled: bool,
    /// Whether the entry shows a check mark.
    pub checked: bool,
}

/// A builder for tray context menus.
///
/// All menu construction is pure data — no Win32 calls — so it is fully
/// testable without a window or message pump.
#[derive(Debug, Clone, Default)]
pub struct TrayMenu {
    entries: Vec<TrayMenuEntry>,
}

impl TrayMenu {
    /// Create an empty menu.
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
        }
    }

    /// Add a simple enabled, unchecked entry.
    pub fn add(&mut self, id: u32, label: &str) {
        self.entries.push(TrayMenuEntry {
            id,
            label: label.to_string(),
            enabled: true,
            checked: false,
        });
    }

    /// Add a visual separator (id 0, empty label).
    pub fn add_separator(&mut self) {
        self.entries.push(TrayMenuEntry {
            id: 0,
            label: String::new(),
            enabled: false,
            checked: false,
        });
    }

    /// Add an entry with a check-mark state.
    pub fn add_checked(&mut self, id: u32, label: &str, checked: bool) {
        self.entries.push(TrayMenuEntry {
            id,
            label: label.to_string(),
            enabled: true,
            checked,
        });
    }

    /// Return a read-only slice of all entries.
    pub fn entries(&self) -> &[TrayMenuEntry] {
        &self.entries
    }

    /// Build the standard Wixen Terminal tray menu.
    ///
    /// Entries: Show/Hide, New Tab, Settings, separator, Exit.
    pub fn build_default_menu() -> Self {
        let mut menu = Self::new();
        menu.add(TRAY_ID_SHOW_HIDE, "Show/Hide");
        menu.add(TRAY_ID_NEW_TAB, "New Tab");
        menu.add(TRAY_ID_SETTINGS, "Settings");
        menu.add_separator();
        menu.add(TRAY_ID_EXIT, "Exit");
        menu
    }
}

/// System tray icon backed by `Shell_NotifyIconW`.
///
/// On [`show`](Self::show), the icon is added to the Windows notification
/// area via `NIM_ADD`. On [`hide`](Self::hide) (or when dropped), it is
/// removed via `NIM_DELETE`.
pub struct TrayIcon {
    hwnd: HWND,
    tooltip: String,
    visible: bool,
    nid: Option<NOTIFYICONDATAW>,
}

impl TrayIcon {
    /// Prepare a tray icon bound to `hwnd` with the given `tooltip`.
    ///
    /// Does **not** call `Shell_NotifyIconW` yet — call [`show`](Self::show)
    /// to make the icon visible.
    pub fn new(hwnd: HWND, tooltip: &str) -> Self {
        info!(tooltip = %tooltip, "Tray icon created (deferred)");
        Self {
            hwnd,
            tooltip: tooltip.to_string(),
            visible: false,
            nid: None,
        }
    }

    /// Show the tray icon in the notification area.
    ///
    /// Calls `Shell_NotifyIconW` with `NIM_ADD` to register the icon. Uses
    /// `IDI_APPLICATION` as a default icon and `WM_TRAY_CALLBACK` as the
    /// callback message for tray interactions.
    pub fn show(&mut self) {
        if self.hwnd == HWND(ptr::null_mut()) {
            warn!("Cannot show tray icon: null HWND");
            return;
        }
        if self.visible {
            return;
        }

        let icon = unsafe { LoadIconW(None, IDI_APPLICATION) };
        let hicon = match icon {
            Ok(h) => h,
            Err(e) => {
                error!(%e, "Failed to load default icon");
                return;
            }
        };

        let nid = NOTIFYICONDATAW {
            cbSize: mem::size_of::<NOTIFYICONDATAW>() as u32,
            hWnd: self.hwnd,
            uID: TRAY_ICON_UID,
            uFlags: NIF_ICON | NIF_TIP | NIF_MESSAGE,
            uCallbackMessage: WM_TRAY_CALLBACK,
            hIcon: hicon,
            szTip: encode_wide_tooltip(&self.tooltip, MAX_TOOLTIP_CHARS),
            ..Default::default()
        };

        let ok = unsafe { Shell_NotifyIconW(NIM_ADD, &nid) };
        if ok.as_bool() {
            self.visible = true;
            self.nid = Some(nid);
            info!("Tray icon shown");
        } else {
            error!("Shell_NotifyIconW(NIM_ADD) failed");
        }
    }

    /// Hide and remove the tray icon from the notification area.
    pub fn hide(&mut self) {
        if let Some(ref nid) = self.nid {
            let ok = unsafe { Shell_NotifyIconW(NIM_DELETE, nid) };
            if !ok.as_bool() {
                warn!("Shell_NotifyIconW(NIM_DELETE) failed");
            }
        }
        self.visible = false;
        self.nid = None;
        info!("Tray icon hidden");
    }

    /// Whether the icon is currently visible.
    pub fn is_visible(&self) -> bool {
        self.visible
    }

    /// The tooltip text shown on hover.
    pub fn tooltip(&self) -> &str {
        &self.tooltip
    }
}

impl Drop for TrayIcon {
    fn drop(&mut self) {
        if self.nid.is_some() {
            self.hide();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── TrayMenu tests ──────────────────────────────────────────────

    #[test]
    fn default_menu_has_expected_entries() {
        let menu = TrayMenu::build_default_menu();
        let entries = menu.entries();

        // Show/Hide, New Tab, Settings, separator, Exit
        assert_eq!(entries.len(), 5);
        assert_eq!(entries[0].label, "Show/Hide");
        assert_eq!(entries[0].id, TRAY_ID_SHOW_HIDE);
        assert_eq!(entries[1].label, "New Tab");
        assert_eq!(entries[2].label, "Settings");
        assert_eq!(entries[3].label, ""); // separator
        assert_eq!(entries[4].label, "Exit");
        assert_eq!(entries[4].id, TRAY_ID_EXIT);
    }

    #[test]
    fn add_and_separator_increase_count() {
        let mut menu = TrayMenu::new();
        assert_eq!(menu.entries().len(), 0);

        menu.add(10, "Alpha");
        assert_eq!(menu.entries().len(), 1);

        menu.add_separator();
        assert_eq!(menu.entries().len(), 2);

        menu.add(11, "Beta");
        assert_eq!(menu.entries().len(), 3);
    }

    #[test]
    fn add_checked_sets_checked_state() {
        let mut menu = TrayMenu::new();
        menu.add_checked(20, "Always on top", true);
        menu.add_checked(21, "Transparency", false);

        assert!(menu.entries()[0].checked);
        assert!(!menu.entries()[1].checked);
        // Both should be enabled.
        assert!(menu.entries()[0].enabled);
        assert!(menu.entries()[1].enabled);
    }

    #[test]
    fn entry_ids_are_stored_correctly() {
        let mut menu = TrayMenu::new();
        menu.add(42, "Foo");
        menu.add(99, "Bar");
        menu.add_checked(7, "Baz", true);

        assert_eq!(menu.entries()[0].id, 42);
        assert_eq!(menu.entries()[1].id, 99);
        assert_eq!(menu.entries()[2].id, 7);
    }

    // ── TrayClickEvent parsing ──────────────────────────────────────

    #[test]
    fn parse_left_click() {
        let lparam = WM_LBUTTONUP as isize;
        assert_eq!(parse_tray_message(lparam), Some(TrayClickEvent::LeftClick));
    }

    #[test]
    fn parse_right_click() {
        let lparam = WM_RBUTTONUP as isize;
        assert_eq!(parse_tray_message(lparam), Some(TrayClickEvent::RightClick));
    }

    #[test]
    fn parse_double_click() {
        let lparam = WM_LBUTTONDBLCLK as isize;
        assert_eq!(
            parse_tray_message(lparam),
            Some(TrayClickEvent::DoubleClick)
        );
    }

    #[test]
    fn parse_unknown_message_returns_none() {
        assert_eq!(parse_tray_message(0), None);
        assert_eq!(parse_tray_message(9999), None);
    }

    #[test]
    fn parse_extracts_low_word_only() {
        // High word should be ignored; low word = WM_RBUTTONUP (517).
        let lparam = (0xDEAD_0000_u32 | WM_RBUTTONUP) as isize;
        assert_eq!(parse_tray_message(lparam), Some(TrayClickEvent::RightClick));
    }

    // ── Tooltip encoding / truncation ───────────────────────────────

    #[test]
    fn tooltip_short_string() {
        let buf = encode_wide_tooltip("Hi", MAX_TOOLTIP_CHARS);
        assert_eq!(buf[0], b'H' as u16);
        assert_eq!(buf[1], b'i' as u16);
        assert_eq!(buf[2], 0); // null-terminated
    }

    #[test]
    fn tooltip_exact_max_length() {
        let text: String = "A".repeat(MAX_TOOLTIP_CHARS);
        let buf = encode_wide_tooltip(&text, MAX_TOOLTIP_CHARS);
        assert_eq!(buf[MAX_TOOLTIP_CHARS - 1], b'A' as u16);
        assert_eq!(buf[MAX_TOOLTIP_CHARS], 0); // null terminator slot
    }

    #[test]
    fn tooltip_truncates_beyond_max() {
        let text: String = "B".repeat(200);
        let buf = encode_wide_tooltip(&text, MAX_TOOLTIP_CHARS);
        // Should have exactly MAX_TOOLTIP_CHARS filled characters.
        assert_eq!(buf[MAX_TOOLTIP_CHARS - 1], b'B' as u16);
        assert_eq!(buf[MAX_TOOLTIP_CHARS], 0);
    }

    #[test]
    fn tooltip_empty_string() {
        let buf = encode_wide_tooltip("", MAX_TOOLTIP_CHARS);
        assert_eq!(buf[0], 0);
    }

    #[test]
    fn tooltip_unicode_chars() {
        // Multi-byte UTF-8 that fits in a single UTF-16 code unit.
        let buf = encode_wide_tooltip("\u{00E9}\u{00F1}", MAX_TOOLTIP_CHARS); // é ñ
        assert_eq!(buf[0], 0x00E9);
        assert_eq!(buf[1], 0x00F1);
        assert_eq!(buf[2], 0);
    }
}
